### ISSUE TITLE
EPIC: Generate QA telemetry data from build system

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-docs#24]
the Makefile should offer a new target: `report` 

- [x] the `qa` target should generate QA telemetry data in JSON format

release history:

- [0.4.0](https://github.com/crate/crate-docs/releases/tag/0.4.0)
  - [x] "last updated" value for each document (per Git log)
  - [x] "last reviewed" value for each document (RST metadata manually maintained by reviewers)
  - [x] run Vale and output the summary results per file

remaining QA telemetry to be implemented:

- [ ] count the number of documents, number of words, and so on
- [ ] count the number of internal links, external links
- [ ] count the number of headings (and maybe distribution of headings)
- [ ] more to come...
